language: android

os: linux

android:
  components:
    - tools
    - build-tools-29.0.2
    - platform-tools
    - android-29

addons:
  sonarcloud:
    organization: "pocketpiglet-github"
    token:
      secure: "ac3oYx8whJj3yN1O5pFNK2Rem0NbQ8ZRwVsvmuFDJ/AreWzP9Gyk2g4U4AsowJbpwQA+ZWOlZv1QkZR2pXBjYz+6z2iJ+2fCNQM6iVUbMkHFIylizh0gMOPjXvZfZP7NumN0RREKff9yFKsrSKmYgKv3zWnVMf8Uas2eLHCmPowV9VOBCjLB4ovAjm2FK2R6dgAbN82uypSufGmx9ZREDOi51Rlv6LJRWEVDWWuD3Z38ry3lu8pdQwz3ohcPdm9IZ7jp5RUCJh0t0I4DMYu1LsBYHanpPIb5Sdksdd+BZ/VFHF/UX2+4kNAaqU80NVX1jOnOJuz3iVQ+mhsx0+E7N4+DrnBsjeBrLIXcstwp9S0c3fhjuy12g/gFPuNZCMjQMBs/z2qvrGS/3KYfp0sveZXCNK0ewIZ+PKpE1fsTpulI0zNY8O2OwTckjt3hHR53mmXDAxg7wwFT41dYIzmDpjlTrvDmYsUfCeDfLf62SOWuhKXJlaGSflOFha39WRt9bhG2+BNqhrkNy6Df3RCXckh4H1X7EXpjxuY68MGcYsM9MSpoqFtcZHza3vXlfhPK/uP1Z1LAlV2gBw4mYuAU9fosB/cgoak9UBwvgSumVlqpaeTt5NOvWrnjFdXRVgAgB+lXIt6wSvWLbg5fPE7muIgzTOonm2kae4lughDR3j4="

install:
  - |
    echo && \
    echo "------ INSTALLATION OF LINUX PACKAGES -----" && \
    echo && \
    sudo apt-get -y install p7zip-full oracle-java8-installer openjdk-11-jdk && \
    echo && \
    echo "------- INSTALLATION OF ANDROID NDK -------" && \
    echo && \
    yes | sdkmanager --verbose "ndk;21.0.6113669" && \
    echo && \
    echo "------- INSTALLATION OF QT PACKAGES -------" && \
    echo && \
    bash tools/install-qt.sh --version 5.12.9 --target android --toolchain android_armv7 --directory "$HOME/Qt" qtbase qtdeclarative qtquickcontrols2 qtmultimedia qtsensors qtpurchasing qtandroidextras && \
    echo && \
    echo "----------- END OF INSTALLATION -----------" && \
    echo

script:
  - |
    echo && \
    echo "---------- ENVIRONMENT VARIABLES ----------" && \
    echo && \
    export JAVA_HOME=/usr/lib/jvm/java-8-oracle && \
    export ANDROID_SDK_ROOT=/usr/local/android-sdk && \
    export ANDROID_NDK_ROOT=/usr/local/android-sdk/ndk/21.0.6113669 && \
    export ANDROID_NDK_HOST=linux-x86_64 && \
    export ANDROID_PLATFORM=android-29 && \
    export PATH=$HOME/Qt/5.12.9/android_armv7/bin:$ANDROID_NDK_ROOT/prebuilt/$ANDROID_NDK_HOST/bin:$PATH && \
    echo && \
    echo "--------- UNSHALLOW GIT FOR SONAR ---------" && \
    echo && \
    git fetch --unshallow && \
    echo && \
    echo "---------- CREATE BUILD DIRECTORY ---------" && \
    echo && \
    mkdir .build && \
    cd .build && \
    echo && \
    echo "------------------ QMAKE ------------------" && \
    echo && \
    qmake ../pocketpiglet.pro && \
    echo && \
    echo "------------------ MAKE -------------------" && \
    echo && \
    make all && \
    echo && \
    echo "-------------- MAKE INSTALL ---------------" && \
    echo && \
    make install INSTALL_ROOT=android-build && \
    echo && \
    echo "------------- ANDROIDDEPLOYQT -------------" && \
    echo && \
    androiddeployqt --input android-libpocketpiglet.so-deployment-settings.json --output android-build --android-platform $ANDROID_PLATFORM --deployment bundled --gradle --no-gdbserver && \
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then \
        echo && \
        echo "-------------- SONAR WRAPPER --------------" && \
        echo && \
        build-wrapper-linux-x86-64 --out-dir bw-output make clean all && \
        echo && \
        echo "-------------- SONAR SCANNER --------------" && \
        echo && \
        cd .. && \
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
        sonar-scanner -Dsonar.projectKey=pocketpiglet_pocketpiglet-android \
                      -Dsonar.projectName="PocketPiglet Android" \
                      -Dsonar.sources=. \
                      -Dsonar.sourceEncoding=UTF-8 \
                      -Dsonar.exclusions="3rdparty/**/*,qml/**/*,translations/*" \
                      -Dsonar.cfamily.build-wrapper-output=.build/bw-output \
                      -Dsonar.cfamily.cache.enabled=false \
                      -Dsonar.cfamily.threads=1 \
                      -Dsonar.java.source=1.7 \
                      -Dsonar.java.binaries=.build; \
    fi
